language: node_js
version: 1.0
node_js:
  - lts/*
script:
  - npm run build
before_deploy:
  - cd public
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    local_dir: build/
    on:
        branch: master
  - provider: npm
    edge: true
    skip_cleanup: true
    email:
      recipients:
        - fch@milestone.dk
        - dao@milestone.dk
        - mss@milestone.dk
    api_key: "$NPM_TOKEN"
    on:
      tags: true
      branch: master