collated: true,
status: 'prototype'
notes: 'Overview of available colors'
preview: '@preview-dark'
context:
  headline: 'Deployment Best Practices'
  content: 'Ask ideas and share ideas and experiences.'
  headlineLong: 'Video Tutorials on Milestone Products'
  inlineCss: ''
